### ISSUE TITLE
How can i analyze sudoku ?

### ISSUE THREAD

**Issue by afkcodes** [1to9only/SukakuExplainer#1]
I tried to analyze sudoku and it gave me the following error:

```
❯ java -Xrs -Xmx500m -cp SukakuExplainer.jar diuf.sudoku.test.Tester puzzles.txt puzzles.log
Error: Could not find or load main class diuf.sudoku.test.Tester
Caused by: java.lang.ClassNotFoundException: diuf.sudoku.test.Tester
```

I tried the `serate`

The puzzle: `...596.....5..4......3..8...7..3.6....87...4..91.....2........1..4.....65.6.1.2.3` gives 1.6 as difficulty on GUI and ED=2.0 in the command line why the difficulty rating are not matching ? Please help me.

**Comment by 1to9only** [comment]
I think you are getting the error message 
```
Error: Could not find or load main class diuf.sudoku.test.Tester
```
because SukakuExplainer.jar is not in your current folder, where presumably you also have puzzles.txt file.

Put one or more puzzles in a file, e.g. puzzles.txt in the example.

I've put your puzzle in a file, and run 
```
java.exe -cp SukakuExplainer.jar diuf.sudoku.test.Tester puzzles.txt puzzles.log
```
and get this output on the screen (also in puzzles.log file)
```
Analyzing Sudoku #1
...596.....5..4......3..8...7..3.6....87...4..91.....2........1..4.....65.6.1.2.3
54 x Hidden Single (1.0-1.5)
3 x Direct Hidden Pair (2.0)
```
In the GUI, you get the same result if you load the puzzle, and  select Tools -> Analyse.

Running serate from the command line
```
java.exe -cp SukakuExplainer.jar diuf.sudoku.test.serate ...596.....5..4......3..8...7..3.6....87...4..91.....2........1..4.....65.6.1.2.3
```
or
```
java.exe -cp SukakuExplainer.jar diuf.sudoku.test.serate --input=puzzles.txt --output=puzzles.se
```
gives this on the screen or in the output file
```
...596.....5..4......3..8...7..3.6....87...4..91.....2........1..4.....65.6.1.2.3 ED=2.0/1.2/1.2
```
ED=2.0 (Direct Hidden Pair) is the highest rated technique needed to solve the puzzle.
The Hint rating shown in GUI is only for the current solving step.

**Comment by 1to9only** [comment]
I've closed this because this not really a problem with the program.

If you need help with SE, you can post to http://forum.enjoysudoku.com/help-with-sudoku-explainer-t6677.html 
where other forum users may be able to offer help.

**Comment by afkcodes** [comment]
Thanks surely will go through the link you have shared, you are amazing as your work on sudoku. i am trying to make a game can you help me with a small thing. Is there any way to connect with you?

**Comment by afkcodes** [comment]
@1to9only is there any way to know the difficulty score of the sudoku puzzle, just like hodoku gives something like 2000 or 2400 with sukakuexplainer or SE
